subscription           = "/subscriptions/SUBSCRIPTION_ID"
role_definition_name   = "Contributor"
rgname                 = "aks-rg"
location               = "us-east1"
service_principal_name = "aks-sp"
keyvault_name          = "aks-kv"